name: Build and Deploy to Azure Container App Job

# push 또는 수동 실행
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# 공통 환경 변수
env:
  AZURE_RESOURCE_GROUP: 'azure_study'
  AZURE_CONTAINERAPP_JOB_NAME : 'my-app-job'
  AZURE_LOCATION: 'eastus'
  CONTAINER_IMAGE_NAME: 'my-app1644'
  ACR_NAME: 'myregistry1644'

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.set-image.outputs.IMAGE_TAG }}
      
    steps:
      # 소스코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure 로그인
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure Container Registry 로그인
      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_TAG ./razorWebApplication1/razorWebApplication1 # dockerfile 존재해야함
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"  # job output으로 설정
        id: set-image

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Azure 로그인
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Container App 업데이트/배포
      - name: Deploy to Azure Container App
        run: |
          az containerapp job update \
            --name ${{ env.AZURE_CONTAINERAPP_JOB_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --image ${{ needs.build-and-push.outputs.image-tag }}
