name: Build and Deploy to Azure Container App Job

# push 또는 수동 실행
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# 공통 환경 변수
env:
  AZURE_RESOURCE_GROUP: 'azure_study'
  AZURE_CONTAINERAPP_NAME: 'my-app-job'
  AZURE_LOCATION: 'eastus'
  CONTAINER_IMAGE_NAME: 'my-app1644'
  ACR_NAME: 'myregistry1644'

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 소스코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure 로그인
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure Container Registry 로그인
      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
          docker build -t $IMAGE_TAG ./razorWebApplication1/razorWebApplication1 # dockerfile 존재해야함
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV  # 다음 단계에서 사용

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Azure 로그인
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Container App 업데이트/배포
      - name: Deploy to Azure Container App
        run: |
          az containerapp job update \
            --name ${{ env.AZURE_CONTAINERAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --image ${{ env.IMAGE_TAG }}
